import { createClient } from '@supabase/supabase-js'
import type { Database } from '@/types/supabase' // Assuming you have a types/supabase.ts generated by Supabase CLI

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY

if (!supabaseUrl || !supabaseAnonKey) {
  throw new Error('Missing Supabase environment variables')
}

// Create a single Supabase client instance for the browser
export const supabase = createClient<Database>(
  supabaseUrl,
  supabaseAnonKey,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true
    }
  }
)

// supabaseAdmin is now handled in server actions/components directly
// to ensure the service role key is never exposed client-side.
